image: docker:24.0.2

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_PROJECT_NAME: myproject

cache:
  paths:
    - frontend/node_modules/
    - backend/vendor/

before_script:
  - apk add --no-cache docker-compose

build_containers:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build
  only:
    - main

run_tests:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d
    - sleep 10  # Laisse le temps aux services de démarrer
    - docker-compose exec frontend npm ci
    - docker-compose exec frontend npx cypress run --browser chrome
    - docker-compose exec backend composer install
    - docker-compose exec backend php bin/phpunit
  after_script:
    - docker-compose -f docker-compose.yml down -v
  artifacts:
    when: always
    paths:
      - frontend/cypress/videos/
      - frontend/cypress/screenshots/
    expire_in: 1 week
  only:
    - main

deploy_to_registry:
  stage: deploy
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker tag frontend $CI_REGISTRY_IMAGE/frontend:latest
    - docker tag backend $CI_REGISTRY_IMAGE/backend:latest
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
    - docker push $CI_REGISTRY_IMAGE/backend:latest
  only:
    - main
