nelmio_cors:
    defaults:
        origin_regex: true                            # Active la prise en charge des expressions régulières dans les origines
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']    # Autorise l'origine définie dans la variable d'environnement CORS_ALLOW_ORIGIN
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']  # Méthodes HTTP autorisées globalement
        allow_headers: ['Content-Type', 'Authorization']                    # Headers autorisés dans les requêtes entrantes
        expose_headers: ['Link']                   # Headers exposés aux navigateurs (disponibles dans les réponses côté client)
        allow_credentials: true                    # Autorise l'envoi de cookies ou d'en-têtes d'authentification
    paths:
        '^/api/':                          # Cible toutes les routes commençant par /api
            origin_regex: true
            allow_origin: ['http://localhost:5173']   # Autorise uniquement les requêtes venant de cette origine (frontend local)
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600                           # Temps en secondes pendant lequel la réponse CORS pré-validée est mise en cache (1h)
            allow_credentials: true

        '^/register':                      # Cible la route d'inscription
            origin_regex: true
            allow_origin: ['http://localhost:5173']
            allow_methods: ['POST', 'OPTIONS']        # Autorise uniquement POST et OPTIONS pour /register
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true

        '^/login':                         # Cible la route de connexion
            origin_regex: true
            allow_origin: ['http://localhost:5173']
            allow_methods: ['POST', 'OPTIONS']        # Autorise uniquement POST et OPTIONS pour /login
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true

