nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        allow_credentials: true
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true
        '^/register':
            origin_regex: true
            allow_origin: ['http://localhost:5173']
            allow_methods: ['POST', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true
        '^/login':
            origin_regex: true
            allow_origin: ['http://localhost:5173']
            allow_methods: ['POST', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true
